# This config file contains the compile options for compilation
# of the EnKF code on the NOAA HPCS.

# ----------------------------------
# Redefine variables for NOAA HPCS
# ----------------------------------
myhome=/work/03337/tg826358/stampede2/nmmb_lib
COREINC  = $(myhome)/incmod
CORELIB  = $(myhome)
#SHTNSLIB = /contrib/pythonextras/Anaconda-1.8.0/lib
INCsfcio = $(COREINC)/sfcio_4
INCsigio = $(COREINC)/sigio_4
INCnetcdf = ${NETCDF}/include
INCnemsio = $(COREINC)/nemsio
 
WRFPATH = /work/03337/tg826358/stampede2/WRFV3.8_GSD_hybridcoord
LIBwrfio_int    = $(WRFPATH)/external/io_int/libwrfio_int.a
LIBwrfio_netcdf = $(WRFPATH)/external/io_netcdf/libwrfio_nf.a
OBJwrf_frame_pk = $(WRFPATH)/frame/pack_utils.o
OBJwrf_sizeof_int = $(WRFPATH)/frame/module_machine.o
WRFLIB = $(LIBwrfio_int) $(LIBwrfio_netcdf) $(OBJwrf_frame_pk) $(OBJwrf_sizeof_int)

NETCDF= /home1/03337/tg826358/softwares/netcdf
INCnetcdf       = ${NETCDF}/include
LIBnetcdf       = -L${NETCDF}/lib -lnetcdf
CRTMLIB   = ${CORELIB}/libcrtm.a
GSILIBS   = -L$(CORELIB) -lw3emc_d -lbufr_v10.2.3_d_64 $(CRTMLIB) $(WRFLIB)

# Empty out definition of libs use by GMAO EnKF building structure
LIBtransf = #-L$(CORELIB) -ltransf
LIBhermes = #-L$(CORELIB) -lhermes
LIBgfio   = #-L$(CORELIB) -lgfio
INChdf    = #-I$(BASEDIR)/$(ARCH)/include/hdf
LIBhdf    = #-L$(BASEDIR)/$(ARCH)/lib  -lmfhdf -ldf -lhdfjpeg -lhdfz -lsz

# ---------------------------
# General targets/definitions
# ---------------------------

  AR     = ar -rv

# ----------------------------
# Fortran compiler and options
# ----------------------------

  CF            = mpif90 -f90=ifort
  FC            = $(CF)

#--- Normal mode options
  PROF= #-pg
  OMP = -qopenmp

  #FFLAGS_F90    = -DGFS   
  #FFLAGS_F90    = -DGFS -DMPI3 # use this if MPI-3 is available (saves memory for LETKF)
  #EXE_FILE = global_enkf
  FFLAGS_F90    = -DWRF   
  EXE_FILE = wrf_enkf
  #FFLAGS_F90    = -DNMMB
  #EXE_FILE = nmmb_enkf

  FFLAGS_COM_N  = -I ./ -I ../ -I $(INCsfcio) -I $(INCsigio) -I $(INCnetcdf) -I $(INCnemsio)\
		-O3 -xHOST -warn all -implicitnone -traceback -fp-model strict -convert big_endian $(OMP)

  FFLAGS_COM_N_NOSWAP  = -I ./ -I ../ -I $(INCsfcio) -I $(INCsigio) -I $(INCnetcdf) -I $(INCnemsio)\
		-O3 -xHOST -warn all -implicitnone -traceback -fp-model strict -convert big_endian $(OMP)

  FFLAGS_N  = $(FFLAGS_F90) $(FFLAGS_COM_N) $(PROF)
  FFLAGS_NOSWAP_N  = $(FFLAGS_F90) $(FFLAGS_COM_N_NOSWAP) $(PROF)
  FFLAGS_f  = $(FFLAGS_COM_N) $(PROF)
  FFLAGS    = $(FFLAGS_N) $(PROF)


#--- Debug mode options
  FFLAGS_COM_D  =  -I ./  -I ../ -I $(INCsfcio) -I $(INCsigio) -I $(INCnetcdf) -I $(INCnemsio)\
		-O0 -xHOST -warn all -implicitnone -traceback -g -debug full -fp-model strict -convert big_endian 
  FFLAGS_COM_NOSWAP_D  =  -I ./ -I ../ -I $(INCsfcio) -I $(INCsigio) -I $(INCnetcdf) -I $(INCnemsio)\
		-O0 -xHOST -warn all -implicitnone -traceback -g -debug full -fp-model strict -convert big_endian

  FFLAGS_D  = $(FFLAGS_F90) $(FFLAGS_COM_D)
  FFLAGS_NOSWAP_D = $(FFLAGS_F90) $(FFLAGS_COM_NOSWAP_D)



# ----------------------
# C Compiler and options
# ----------------------

  CC            = gcc

#--- Normal mode options

  CFLAGS_N      = -DLINUX -Dfunder -I ./ -DFortranByte=char -DFortranInt=int -DFortranLlong='long long' -O3 $(PROF)

#--- Debug mode options

  CFLAGS_D      = -DLINUX -Dfunder -I ./ -DFortranByte=char -DFortranInt=int -DFortranLlong='long long' -g


# ------------------
# Linker and options
# ------------------

  LD            = $(CF) 

#--- Normal mode options
  LIBS_N        = -L$(CORELIB) -lsp_v2.0.1_d -lsigio_4 -lsfcio_4 -lnemsio -lbacio_4 -lw3nco_d $(GSILIBS)\
     	  -L$(NETCDF)/lib -lnetcdf
  # use this one if linking shtns lib intead of splib for spectral transforms.
  #LIBS_N        = -L$(CORELIB) -lsp_v2.0.1_d -lsigio_4 -lsfcio_4 -lnemsio -lbacio_4 -lw3nco_d\
  # 		  $(GSILIBS) -L$(NETCDF)/lib -lnetcdf -L$(SHTNSLIB) -lshtns -lfftw3

  LDFLAGS_N     = -mkl=sequential $(OMP)

  LDFLAGS       = $(LDFLAGS_N)

#--- Debug mode options

  LIBS_D        = $(LIBS_N)

  LDFLAGS_D     = $(LDFLAGS_N)

#--- Empty out mpi library definition: embedded in compiler

  LIBmpi	=
